apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_rdma1
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "delegates": [
          {
                  "cniVersion": "0.3.1",
                  "type": "sbr",
                  "name": "sbr"
          }
  ]
}'

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net2
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_rdma2
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "delegates": [
          {
                  "cniVersion": "0.3.1",
                  "type": "sbr",
                  "name": "sbr"
          }
  ]
}'

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net3
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_rdma3
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "delegates": [
          {
                  "cniVersion": "0.3.1",
                  "type": "sbr",
                  "name": "sbr"
          }
  ]
}'

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net4
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_rdma4
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "delegates": [
          {
                  "cniVersion": "0.3.1",
                  "type": "sbr",
                  "name": "sbr"
          }
  ]
}'
